nameUser = input("What is your name? ")
ageUser = input("How old are you? ")
cityUser = input("Where are you live? ")
print("This is {0}.".format(nameUser))
print("It is {0}.".format(ageUser))
print("(S)he live in {0}.".format(cityUser))